name: activos_fijos_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http: ^0.13.4
  provider: ^6.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - lib/Utils/Images/
  fonts:
    - family: NoirPro
      fonts:
        - asset: lib/Utils/Fonts/NoirPro-Light.ttf
        - asset: lib/Utils/Fonts/NoirPro-Medium.ttf
        - asset: lib/Utils/Fonts/NoirPro-Regular.ttf
